services:
  web-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - 8050:8050
    depends_on:
      - callback-worker 
      - query-worker 
      - cache
    env_file:
      - ./env.list
    environment:
      REDIS_SERVICE_HOST: cache
      REDIS_SERVICE_PORT: 6379
    restart: always

  callback-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    depends_on:
      - cache
    env_file:
      - ./env.list
    environment:
      REDIS_SERVICE_HOST: cache
      REDIS_SERVICE_PORT: 6379
    restart: always

  query-worker:
    build:
      context: .
      dockerfile: Dockerfile.data_worker
    depends_on:
      - cache
    env_file:
      - ./env.list
    environment:
      REDIS_SERVICE_HOST: cache
      REDIS_SERVICE_PORT: 6379
    restart: always

  cache:
    image: redis
    ports:
      - 6379:6379
    restart: always

  flower:
    build:
      context: .
      dockerfile: Dockerfile.flower
    depends_on:
      - callback-worker
      - query-worker
      - cache
      - web-server
    env_file:
      - ./env.list
    environment:
      REDIS_SERVICE_HOST: cache
      REDIS_SERVICE_PORT: 6379
    ports:
      - 5555:5555
